import os

Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'MP3Decoder'
group['CCFLAGS'] = ''
group['CPPPATH'] = [os.getcwd() + '/pub', os.getcwd() + '/real']
group['CPPDEFINES'] = []
group['LINKFLAGS'] = ''

src = Split("""
mp3dec.c
mp3tabs.c
real/bitstream.c
real/buffers.c
real/dct32.c
real/dequant.c
real/dqchan.c
real/huffman.c
real/hufftabs.c
real/imdct.c
real/scalfact.c
real/stproc.c
real/subband.c
real/trigtabs.c
real/arm/asmpoly_thumb2.s
real/arm/asmmisc.s
""")

group['src'] = File(src)

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

obj = env.Object(group['src'])

Return('obj')
