import os
Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'DeviceDrivers'

group['src'] = Glob(RTT_ROOT + '/rt-thread/components/drivers/spi/*.c')
group['CCFLAGS'] = ''
group['CPPPATH'] = [RTT_ROOT + '/rt-thread/components/drivers/include']
group['CPPDEFINES'] = ''
# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
#env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
