import os

Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'Startup'
group['CCFLAGS'] = ''
group['CPPPATH'] = [os.getcwd()]
group['CPPDEFINES'] = ['USE_STDPERIPH_DRIVER', rtconfig.STM32_TYPE]
group['LINKFLAGS'] = ''

src = Glob('*.c') + Glob('fmt0371/*.c') + Glob('ili9325/*.c')

gui_src = Split('''
demo_fnview.c
demo_listview.c
demo_listview_icon.c
demo_panel_single.c
demo_simple_workbench.c
demo_view.c
demo_view_animation.c
demo_view_benchmark.c
demo_view_box.c
demo_view_buffer_animation.c
demo_view_button.c
demo_view_checkbox.c
demo_view_combobox.c
demo_view_dc.c
demo_view_dc_buffer.c
demo_view_image.c
demo_view_instrument_panel.c
demo_view_label.c
demo_view_listbox.c
demo_view_listctrl.c
demo_view_menu.c
demo_view_module.c
demo_view_mywidget.c
demo_view_notebook.c
demo_view_progressbar.c
demo_view_radiobox.c
demo_view_scrollbar.c
demo_view_slider.c
demo_view_textbox.c
demo_view_ttf.c
demo_view_window.c
demo_workbench.c
demo_xml.c
gui_init.c
mywidget.c
''')

for index in range(0, len(gui_src)):
	gui_src[index] = RTT_ROOT + '/rt-thread/examples/gui/' + gui_src[index]

group['src'] = src + File(gui_src)

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

obj = env.Object(group['src'])

Return('obj')
