Import('env')
Import('projects')
Import('RTT_ROOT')
Import('rtconfig')

# group definitions
group = {}
group['name'] = 'STM32'
if rtconfig.CROSS_TOOL == 'keil':
	group['src'] = Glob('*.c') + Glob('*_rvds.S')
else:
	group['src'] = Glob('*.c') + Glob('*_gcc.S')
group['CCFLAGS'] = ''
group['CPPPATH'] = [RTT_ROOT + '/rt-thread/stm32']
group['CPPDEFINES'] = ''
group['LINKFLAGS'] = ''

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
